andres_mazza_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: AndresMazzaUserBundle:Default:index }

andres_mazza_user_index:
    path:   /user/index
    defaults: { _controller: AndresMazzaUserBundle:User:index}


andres_mazza_user_articles:
    path:   /user/articles/{page}
    defaults: { _controller: AndresMazzaUserBundle:User:articles, page:1}
    requirements:
        page: \d+

andres_mazza_user_add:
    path:   /user/add
    defaults: { _controller: AndresMazzaUserBundle:User:add }

andres_mazza_user_edit:
    path:   /user/edit/{id}
    defaults: { _controller: AndresMazzaUserBundle:User:edit }
    requirements:
        id: \d+

andres_mazza_user_view:
    path:   /user/view/{id}
    defaults: { _controller: AndresMazzaUserBundle:User:view }
    requirements:
        id: \d+

andres_mazza_user_delete:
    path:   /user/delete/{id}
    defaults: { _controller: AndresMazzaUserBundle:User:delete }
    requirements:
        id: \d+
